### PR TITLE
fix(outline): external label resize

### LINKED ISSUE #2001: External label selection outline is incorrect after label is created or modified
### Describe the Bug

Given I add an external label (e.g. to an event or a gateway), its selection outline is much bigger than necessary, and it doesn't follow the XML bounds. Also for labels already existing in the diagram, the outline is not updated.

### Steps to Reproduce

1. Create an external label
2. Select it

https://github.com/bpmn-io/bpmn-js/assets/28307541/e9df1a46-68e1-423c-89e0-0bd8795d6b0a

or

1. Modify an existing external label
2. Select it

https://github.com/bpmn-io/bpmn-js/assets/28307541/1506dcc3-ea2b-4427-8f1e-e0874ce33aee

### Expected Behavior

It should follow the bounds / label size.

### Environment

 - Browser: [e.g. IE 11, Chrome 69]
 - OS: [e.g. Windows 7]
 - Library version: v15.0.0

### PR DESCRIPTION
**Pull request by smbea**
Closes #2001

### CODE REVIEW

File: test/spec/features/outline/OutlineProviderSpec.js [hunk 1]
```diff
@@ -118,17 +121,44 @@ describe('features/outline - outline provider', function() {
...
+        selection.select(externalLabel);
+        var outlineShape = domQuery('.selected .djs-outline', outlineShape);
+
+        // then
+        let bounds = outlineShape.getBoundingClientRect();
+        expect(bounds.width).to.be.closeTo(34, DELTA);
+        expect(bounds.height).to.be.closeTo(24, DELTA);
+
+        // when
+        modeling.updateLabel(externalLabel, 'fooooooooooooooo');
```
Comment (barmac) [inline test/spec/features/outline/OutlineProviderSpec.js:143]: I like this test case :D

**Comment by barmac** [comment]
Changing target to `master`.

**Review by barmac — APPROVED** [review]
