### PR TITLE
fix(moddle-copy): primitive array copying

### LINKED ISSUE #1518: `bpmnReplace` fails when custom meta model uses a `String` array
__Describe the Bug__

I am using a custom meta model that has a property of type `String` and `isMany` set to true. I am attempting to call `bpmnReplace` (from `modeler.get("bpmnReplace")`) and an error is being thrown when the element is being copied:

The error prevents the element from being replaced.

I set up an example reproduction using one of the bpmn example [repos](https://github.com/bpmn-io/bpmn-js-example-react-properties-panel). Here's a [fork](https://github.com/alexbisaillion/bpmn-js-example-react-properties-panel) of it.

It is worth noting that the example repo was using bpmn-js v3.2.1, where the issue does not happen:

It happens with v8.8.2, so it looks like it is a regression.

__Steps to Reproduce__

1. Clone my example repo available [here](https://github.com/alexbisaillion/bpmn-js-example-react-properties-panel)
2. Run the example as normal (`npm install && npm start`)
3. Click the "Do work" task
4. Click "Make task" in the properties panel. The call to `bpmnReplace` will fail.

__Expected Behavior__

The task should be replaced successfully.

__Environment__

 - Browser: Chrome Version 95.0.4638.54
 - OS: Windows 10
 - Library version: 8.8.2

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #1518

Issue stemmed from setting the parent here. When the array contained primitives, this led to trying to set a property on a primitive which is an exception. In general, the recursion itself handled the setting (or not) of parents depending on the array element type, so doing it here again is (unless I've missed something) redundant and in this case breaking.

Also thanks @pinussilvestrus for the test case.

### CODE REVIEW

File: lib/features/copy-paste/ModdleCopy.js [hunk 1]
```diff
@@ -234,8 +234,6 @@ ModdleCopy.prototype.copyProperty = function(property, parent, propertyName) {
 
       // copying might NOT be allowed
       if (copiedProperty) {
-        copiedProperty.$parent = parent;
-
```
Comment (pinussilvestrus) [inline lib/features/copy-paste/ModdleCopy.js:238]: Do we know why we had this in the first place? I think we introduced it via multi-elements copy-paste, but it seems like it's not necessary (/cc @philippfromme). 

It looks good interaction wise and also CI is green.

Comment (Skaiir) [reply lib/features/copy-paste/ModdleCopy.js:238]: I think it probably was an oversight from how the code is structured but I may be missing something, kinda why I invited flip too. In any case it would be good to find that out, because if there's an issue here we need to write some more tests to cover the cases.

Comment (Skaiir) [reply lib/features/copy-paste/ModdleCopy.js:238]: I think it probably was an oversight from how the code is structured but I may be missing something, kinda why I invited flip too. In any case it would be good to find that out, because if there's an issue here we need to write some more tests to cover the cases.

**Comment by pinussilvestrus** [comment]
I would be fine with merging it. @philippfromme feel free to give it a final thought (cf. https://github.com/bpmn-io/bpmn-js/pull/1647#discussion_r874781401) 👍

File: lib/features/copy-paste/ModdleCopy.js (hunk 1 above)
Comment (philippfromme) [reply lib/features/copy-paste/ModdleCopy.js:238]: `$parent` should only be set if `copiedProperty.$type` exists which means it's a moddle element. This issue didn't pop up for a long time because in the standard model all arrays of properties contain only moddle elements (e.g. `extensionElements.values`).

**Review by philippfromme — APPROVED** [review]
Good job! 🚀
