### PR TITLE
fix(create-append-anything): disallow append menu for connections

### LINKED ISSUE #1813: Append anything breaks modeler when triggered from connection
Found a way to break it:

https://user-images.githubusercontent.com/28307541/214008728-9347dc1e-34b6-4ad0-8422-794fc74457e1.mov

Easy way to fix this is to disable this functionality for all connections.

_Originally posted by @barmac in https://github.com/bpmn-io/bpmn-js/issues/1811#issuecomment-1400055382_

### PR DESCRIPTION
**Pull request by smbea**
Closes #1813

### CODE REVIEW

File: test/spec/features/create-append-anything/AppendRulesSpec.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ describe('features/create-append-anything - rules', function() {
 
   var testModules = [ modelingModule, coreModule, rulesModule, createAppendAnything ];
 
-  var testXML = require('./AppendMenuProvider.bpmn');
+  var testXML = require('./AppendRules.bpmn');
```
Comment (nikku) [inline test/spec/features/create-append-anything/AppendRulesSpec.js:16]: :+1:

**Review by nikku — APPROVED** [review]

**Review by barmac — APPROVED** [review]
Great contribution!

**Comment by barmac** [comment]
What I liked a lot is the exhaustive test suite which describes the requirements, nothing less and nothing more.
