### PR TITLE
fix(modeling): allways create Categories in `definitions`

### LINKED ISSUE #1606: Creating groups inside collapsed sub-processes breaks BPMN export
__Describe the Bug__

If I create a group inside a collapsed sub-process and save the result a warning shows on re-import:

```
unresolved reference <CategoryValue_01k5toe>
```

__Steps to Reproduce__

1. Model an embedded, collapsed sub-process and navigate to it
2. Add a group to the collapsed sub-process
3. Save the diagram
4. Re-import the diagram
5. __See the warning above `unresolved reference <CategoryValue_01k5toe>`__

__Expected Behavior__

Modeling groups does work without warnings.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: v9.0.1

----

image

image

### PR DESCRIPTION
**Pull request by marstamm**
closes #1606

We assumed that `definitions` is always the parent of the root element. This is not the case in subprocess planes.

Replaced the assumptions with a call to get the `getDefinitions()` method on the viewer.

### CODE REVIEW

File: lib/features/modeling/behavior/GroupBehavior.js [hunk 1]
```diff
@@ -24,26 +24,14 @@ var HIGH_PRIORITY = 2000;
...
 ) {
   injector.invoke(CommandInterceptor, this);
 
-  /**
-   * Gets process definitions
-   *
-   * @return {ModdleElement} definitions
-   */
-  function getDefinitions() {
-    var rootElement = canvas.getRootElement(),
```
Comment (nikku) [inline lib/features/modeling/behavior/GroupBehavior.js:41]: Why not simply change this method with a call to `bpmnjs.getDefinitions()`?

Keeps the "how to get the definitions" in a single place.

Comment (marstamm) [reply lib/features/modeling/behavior/GroupBehavior.js:41]: The method just felt unnecessary when we are using the viewer API directly. We do use them directly in other parts of our code base, like the [RootElementReferenceBehavior](https://github.com/bpmn-io/bpmn-js/blob/9e313273353ed1530958a9ee9d54368cd4d7581c/lib/features/modeling/behavior/RootElementReferenceBehavior.js#L49)

Comment (nikku) [reply lib/features/modeling/behavior/GroupBehavior.js:41]: Works for me!
