### PR TITLE
fix(replace): persist multi-instance props with `isSequential` change

### LINKED ISSUE #1581: Multi-Instance Properties Lost When Changing Between Parallel and Sequential
__Describe the Bug__

bvc7qV9Mw8

__Steps to Reproduce__

1. Create sub-process
2. Add parallel multi-instance
3. Add loop cardinality
4. Change to sequential multi-instance
5. Multi-instance properties lost

__Expected Behavior__

Multi-instance properties not lost.

__Environment__

 - Library version: 8.9.0

---

Reported through https://forum.bpmn.io/t/how-to-save-elements-when-changing-task-settings/7092/7

### PR DESCRIPTION
**Pull request by smbea**
Closes #1581

### CODE REVIEW

File: test/spec/features/popup-menu/ReplaceMenuProviderSpec.js [hunk 1]
```diff
@@ -583,6 +592,35 @@ describe('features/popup-menu - replace menu provider', function() {
         expect(domClasses(parallelEntry).has('active')).to.be.false;
       }));
 
+
+      it('should keep parallel properties', inject(function(bpmnReplace, elementRegistry) {
```
Comment (marstamm) [inline test/spec/features/popup-menu/ReplaceMenuProviderSpec.js:596]: Should we also have a test for the other way (sequential -> parallel)?

File: test/spec/features/popup-menu/ReplaceMenuProviderSpec.js [hunk 2]
```diff
@@ -583,6 +592,64 @@ describe('features/popup-menu - replace menu provider', function() {
...
+            businessObject = getBusinessObject(task),
+            loopCharacteristics = Object.assign({}, businessObject.loopCharacteristics);
+
+        openPopup(task);
+
+        // assume
+        expect(loopCharacteristics.isSequential).to.be.true;
+
+        // when
+        triggerAction('toggle-parallel-mi');
```
Comment (marstamm) [inline test/spec/features/popup-menu/ReplaceMenuProviderSpec.js:638]: This test should be part of `describe('parallel toggle button', ...)`

**Review by marstamm — APPROVED** [review]
:clap: Nice one!
