### PR TITLE
fix(drilldown): allow navigation to root collaboration

### LINKED ISSUE #1566: Cannot drill out after root change
__Describe the Bug__

Once I wrapped the process with a pool, moved into a sub-process and drill out an error is thrown:

```
Canvas.js?c639:626 Uncaught Error: rootElement required
    at Canvas.setRootElement (Canvas.js?c639:626:1)
    at HTMLLIElement.eval (DrilldownBreadcrumbs.js?6780:32:1)
```

As it looks like the drilldown overlay is not aware of root changes going on.

capture 4HeFbO_optimized

__Steps to Reproduce__

1. wrap collapsed sub-process with pool
2. navigate into collapsed sub-process
3. try move back to parent process
4. __Error is emitted__

__Expected Behavior__

Drilldown is fully aware of root element changes; I am able to move back up.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `bpmn-js@develop`

### PR DESCRIPTION
**Pull request by marstamm**
closes #1566

### CODE REVIEW

**Comment by nikku** [comment]
Could you quickly elaborate on what you fixed and why it works? That would help me :).

**Comment by marstamm** [comment]
We build the parent chain for the Breadcrumbs using the Business Object Chain. When the root is a Collaboration, the root element is the Process.

When we have a collaboration, this Process does not have a corresponding Element in the ElementRegisty/Canvas.
For this edge case, we now search for the Participant which references the Process and use the Plane/RootElement that contains the participant instead

File: lib/features/drilldown/DrilldownBreadcrumbs.js [hunk 1]
```diff
@@ -21,15 +21,28 @@ export default function DrilldownBreadcrumbs(eventBus, elementRegistry, overlays
...
+    var path = parents.map(function(parent) {
+      var title = escapeHTML(parent.name || parent.id);
       var link = domify('<li><span class="bjs-crumb"><a title="' + title + '">' + title + '</a></span></li>');
 
+      var parentPlane = canvas.findRoot(planeId(parent)) || canvas.findRoot(parent.id);
+
+      if (!parentPlane && is(parent, 'bpmn:Process')) {
+
+        // root is a collaboration
+        var participant = elementRegistry.find(function(element) {
```
Comment (nikku) [inline lib/features/drilldown/DrilldownBreadcrumbs.js:36]: Instead of searching through all diagram elements like this, can't we search through all roots to find the element (participant _or_ process backed element) that references the diagram? It is a difference between searching through 5 or 500 elements, every time we update.

Also, I'd personally expect the magic to happen in `getParentChain`, not in the code boostrapping the HTML. But that is just a personal preference.

Comment (marstamm) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: > can't we search through all roots
Fair point, I will adjust it 👍

> I'd personally expect the magic to happen in `getParentChain`
I'd argue that `getParentChain` gives us the execution semantics and the actual linking to the corresponding planes should happen somewhere else

Comment (nikku) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: As both are personal preference I#d love to get your feedback. Happy to merge things as is (and see how they evolve over time, too).

We could add a comment like https://github.com/bpmn-io/bpmn-js/pull/1567#issuecomment-1011361926 or make the variables easier to grasp (i.e. rename parent to `parentBo`) to outline which problem this piece of code solves.

Comment (nikku) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: Maybe `parentBoChain` will make it clearer that we are dealing with parent hierarchy entirely on the business object level here (and must compensate for the case where the business object does not have a direct graphical represnetation, but one linked through the displayed participant).

Comment (marstamm) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: > can't we search through all roots

On second thought, the root element is the Collaboration, not the Participant, and does not have a direct link to the Processes. We also have to check that it is the correct Collaboration in Case we have a multi-Collaboration-Diagram.

So the logic here would be more complex if we went for root elements. As this is only done once every drilldown and not every render, let's keep the logic "simple", even when it's less efficient.

Comment (marstamm) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: I'll look into explaining the magic in the code tomorrow (:

Comment (marstamm) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: Added documentation with dfe2f8eb5ffd204faa1b6808b250ec48470a39c6

Comment (nikku) [reply lib/features/drilldown/DrilldownBreadcrumbs.js:36]: :tada:

**Review by nikku — APPROVED** [review]
