### PR TITLE
fix: move labels to new plane when collapsing sub process

### LINKED ISSUE #1695: Sub process: visible label(s) after changing to collapsed sub process
Visible label(s) after changing to collapsed sub process with start, task and end event inside. 
The label of the start event is even moving far more outside.

This issue occures only by clicking the steps through. Import and Export of the diagram works proberly.
It is tricky to reproduce. See the uploaded gif animation for detailed steps.

__Steps to Reproduce__

1. append task and end event
2. change task to sub process (expanded)
3. append task and end event in the sub process
4. Add labels to start, task and end event
5. Click on collapsed sub process

Hint: Its not quite clear if the start event inside the sub process may or may not be moved in order to reproduce the error.

bpmn-io-subprocess

__Expected Behavior__

Hide the label inside the sub process.

__Environment__

 - Browser: [Chrome 69 103.0.5060.66 (Offizieller Build) (64-Bit), Edge 103.0.1264.49 (Offizielles Build) (64-Bit)]
 - OS: [e.g. Windows 10]

### PR DESCRIPTION
**Pull request by philippfromme**
brave_rFwQiwTdGP

---

Closes #1695

### CODE REVIEW

**Review by nikku — APPROVED** [review]

File: lib/features/modeling/behavior/SubProcessPlaneBehavior.js [hunk 1]
```diff
@@ -411,6 +411,15 @@ SubProcessPlaneBehavior.prototype._moveChildrenToShape = function(source, target
     return;
   }
 
+  // add external labels that weren't children of sub process
+  children = children.concat(children.reduce((labels, child) => {
```
Comment (nikku) [inline lib/features/modeling/behavior/SubProcessPlaneBehavior.js:415]: PhantomJS does not approve this closure. :wilted_flower:

**Review by nikku — APPROVED** [review]

File: lib/features/modeling/behavior/SubProcessPlaneBehavior.js (hunk 1 above)
Comment (philippfromme) [reply lib/features/modeling/behavior/SubProcessPlaneBehavior.js:415]: Argh!
