### PR TITLE
fix(drilldown): don't reset vieport on `makeCollaboration`

### LINKED ISSUE #1565: Diagram jumps wrapping process in pool
__Describe the Bug__

capture gstW3T_optimized

__Steps to Reproduce__

1. model process
2. wrap in pool
3. __See diagram jump__

__Expected Behavior__

Diagram stays in current viewport.

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `bpmn-js@develop`

### PR DESCRIPTION
**Pull request by marstamm**
closes #1565

Idea here: A Collaboration is always the root, so it will have a stored Viewbox when it accessed via 'drillUp'. We can safely assume that we want to keep the viewbox otherwise.

A cleaner solution would be to introduce a `hints` Object on the `setRootElement` API and add `{keepViewbox: true}` when we replace it in:
https://github.com/bpmn-io/bpmn-js/blob/4e08a1c703e71866ef1b11d2196daa2374a618ec/lib/features/modeling/cmd/UpdateCanvasRootHandler.js#L66-L68

However, this requires some changes in diagram-js, so I decided to go for the easy fix.

### CODE REVIEW

**Comment by barmac** [comment]
Found a bug which is probably due to the branch not being on top of `develop`:

https://user-images.githubusercontent.com/28307541/149358154-7188166b-1b3c-4be9-afa1-4594ef19eb16.mov

I think this was fixed via https://github.com/bpmn-io/bpmn-js/pull/1567 so can you please rebase your branch?

**Comment by marstamm** [comment]
I rebased it :+1:

**Comment by barmac** [comment]
While this works just after I change the diagram to collaboration, the viewport is still reset once I collapse a subprocess. Does it make sense?

https://user-images.githubusercontent.com/28307541/149491012-1b2257e5-b06d-4cd9-b7b8-eb26a0015cb8.mov

**Comment by marstamm** [comment]
Thanks for the review! It does not make sense, so I pushed a fix and added a test for it as well

File: lib/features/drilldown/DrilldownCentering.js [hunk 1]
```diff
@@ -36,12 +46,6 @@ export default function DrilldownCentering(eventBus, canvas) {
     if (storedViewbox.zoom !== currentViewbox.scale) {
       canvas.zoom(storedViewbox.zoom, { x: 0, y: 0 });
     }
-
-    currentRoot = newRoot;
-  });
-
-  eventBus.on('root.remove', function(event) {
-    positionMap.remove(event.element);
   });
```
Comment (marstamm) [inline lib/features/drilldown/DrilldownCentering.js:49]: We need to store the viewbox after removal in case `undo` is called

**Review by barmac — APPROVED** [review]
It seems to work. LGTM
