### PR TITLE
1072 sequence flow has wrong parent after replacement

### LINKED ISSUE #1072: Sequence Flow has wrong parent or crashes modeler after replacement
__Describe the Bug__

It looks like we do not put the new connection in the appropriate target if we replace a message flow with a sequence flow.

The modeler stops to work when you the previous connection source is a Participant.

__Working Interaction (bpmn-js@3.3.x)__

old

__Broken Interaction (`master` branch)__

new

__Steps to Reproduce__

* Open [this test diagram](https://github.com/bpmn-io/bpmn-js/files/3265424/test.bpmn.txt)
* Reconnect message flow start to task end (creating a loop)
* Observe sequence flow not being part of second participant

__Expected Behavior__

* Sequence Flow is part of second participant / process and rendered accordingly

__Environment__

 - Browser: Any
 - OS: Any
 - Library version: `master`

### PR DESCRIPTION
**Pull request by barmac**
Closes #1072

### CODE REVIEW

File: test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js [hunk 1]
```diff
@@ -553,4 +553,79 @@ describe('features/modeling - replace connection', function() {
...
+    );
+
+  });
+
+});
+
+
+
+// helper /////
+function getMid(bounds) {
```
Comment (pinussilvestrus) [inline test/spec/features/modeling/behavior/ReplaceConnectionBehaviorSpec.js]: Why not simply using [`LayoutUtil#getMid`](https://github.com/bpmn-io/diagram-js/blob/master/lib/layout/LayoutUtil.js#L74)? Seems like doing the same.
