### PR TITLE
Event references not removed when element is replaced

### LINKED ISSUE #2249: Global references are not kept when replacing an event (interrupting to non-interrupting)
### Describe the Bug

I replace an event (i.e. a boundary event) from interrupting to non-interrupting. I see that the global message reference gets lost.

We have existing test cases for the desired behavior (reference is kept), but due to nested `it(..., function() { it(...); }` calls these are not actually executed :see_no_evil:.

https://github.com/bpmn-io/bpmn-js/pull/2248 uncovered this miss-use, and the bug.

### Steps to Reproduce

1. Uncomment [these tests](https://github.com/bpmn-io/bpmn-js/pull/2248/files#diff-2b6a392f65b0662ea3d4aa7ec6615a0a086247b6480e00d6ce94b10408597657R67)
2. See that test suite fails

### Expected Behavior

When replacing an event (toggling interrupting / non-interrupting) we keep the global element reference.

### Environment

 - Browser: Any
 - OS: Any
 - Library version: v17.1.0

---

Related to https://github.com/bpmn-io/bpmn-js/issues/1906

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #2249, #1906
Related to: https://github.com/camunda/camunda-modeler/issues/4863, https://github.com/camunda/camunda-modeler/issues/4567
### Proposed Changes
Event references now retain the same reference even when the associated element is changed.

Specifically handled event definitions:

- `bpmn:ErrorEventDefinition`
- `bpmn:EscalationEventDefinition`
- `bpmn:MessageEventDefinition`
- `bpmn:SignalEventDefinition`

 
Apr-15-2025 19-53-02

You can try it out via 
```
npx @bpmn-io/sr camunda/camunda-bpmn-js -l bpmn-io/bpmn-js#event-refs
```
### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [x] **Visual demo** attached
* [x] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: lib/util/DiUtil.js [hunk 1]
```diff
@@ -120,3 +121,19 @@ export function hasEscalationEventDefinition(element) {
...
   return hasEventDefinition(element, 'bpmn:CompensateEventDefinition');
 }
+
+/**
+ * @param {ModdleElement} moddleElement
+ * @param {string[]} types
+ *
+ * @return {boolean}
+ */
+export function hasAnyEventDefinition(moddleElement, types) {
```
Comment (philippfromme) [inline lib/util/DiUtil.js:131]: This check isn't related to DI so it should be somewhere else.

File: lib/features/copy-paste/ModdleCopy.js [hunk 2]
```diff
@@ -197,8 +200,16 @@ ModdleCopy.prototype.copyProperty = function(property, parent, propertyName, clo
 
   var propertyDescriptor = this._moddle.getPropertyDescriptor(parent, propertyName);
 
-  // do NOT copy references
+  // do NOT copy references except given event definitions
   if (propertyDescriptor.isReference) {
+    if (hasAnyEventDefinition(parent, [
```
Comment (philippfromme) [inline lib/features/copy-paste/ModdleCopy.js:205]: Doesn't this mean we copy _any_ reference if an element has a given event definition? We only want to copy errors, messages and signals.

Also, I probably would't change this file, We support hooking in through events already and we're making use of this in [other places](https://github.com/camunda/camunda-bpmn-js-behaviors/blob/main/lib/camunda-cloud/CopyPasteBehavior.js). So instead I'd create a default behavior that implements copying these references.

**Review by philippfromme — CHANGES_REQUESTED** [review]
Couple of remarks.

File: lib/features/copy-paste/ModdleCopy.js (hunk 2 above)
Comment (abdul99ahad) [reply lib/features/copy-paste/ModdleCopy.js:205]: I think that `canCopyProperty` behavior already allows to copy references. Earlier, we were handling references in `copyProperty` method in this file.  
https://github.com/bpmn-io/bpmn-js/blob/61ee0d4255cc3bd25473833beb440ea09bd77731/lib/features/copy-paste/ModdleCopy.js#L204

Comment (abdul99ahad) [reply lib/features/copy-paste/ModdleCopy.js:205]: It checks whether the property is of reference `propertyDescriptor.isReference`, and if so it just returns so the reference property will not be copied to the target element. 

This functionality is applied in [bpmn-js/lib/features/copy-paste/ModdleCopy.js](https://github.com/bpmn-io/bpmn-js/blob/61ee0d4255cc3bd25473833beb440ea09bd77731/lib/features/copy-paste/ModdleCopy.js#L204) so I bypass it in the same location.

Comment (philippfromme) [reply lib/features/copy-paste/ModdleCopy.js:205]: I'm not sure I can follow.

1. What I mean is to add this:

```javascript
// BpmnCopyPaste.js

eventBus.on('moddleCopy.canCopyProperty', ({ property }) => {
  if (isAny(property, [
    'bpmn:Error',
    'bpmn:Message',
    'bpmn:Signal'
  ])) return property;
});
```
2. Again, you're checking only the event definition's type not for the referenced element's type so you'd copy _any_ reference the event definition might have.

Comment (abdul99ahad) [reply lib/features/copy-paste/ModdleCopy.js]: Added check for event definition type and referenced element type.

**Review by jarekdanielak — CHANGES_REQUESTED** [review]
I strongly agree on Philipp's suggestion to take your logic out of the core `ModdleCopy`.

**Comment by abdul99ahad** [comment]
> I strongly agree on Philipp's suggestion to take your logic out of the core ModdleCopy.

The reason I implemented this in `bpmn-js` is because `camunda-bpmn-js-behaviors` is only used in `camunda-bpmn-js`. If I run `bpmn-js` standalone, the behavior will be the same (i.e., can't reference the element after element change), unless I'm missing something here 😕

**Comment by jarekdanielak** [comment]
You might've missed a sneaky comment in Philipp's snippet, but he suggested to move it to BpmnCopyPaste.js for starters. 😄

**Comment by abdul99ahad** [comment]
> You might've missed a sneaky comment in Philipp's snippet, but he suggested to move it to BpmnCopyPaste.js for starters. 😄

`BpmnCopyPaste.js` have copypaste behaviors only. If we are dealing events of `moddleCopy.canCopyProperty`. Why not implement this in `ModdleCopy` file?

**Comment by philippfromme** [comment]
Might make more sense to move it to the top of [ModdleCopy](https://github.com/bpmn-io/bpmn-js/blob/main/lib/features/copy-paste/ModdleCopy.js#L47) but I generally would want handling exceptions to not be buried in the code.

**Comment by abdul99ahad** [comment]
> Might make more sense to move it to the top of [ModdleCopy](https://github.com/bpmn-io/bpmn-js/blob/main/lib/features/copy-paste/ModdleCopy.js#L47) but I generally would want handling exceptions to not be buried in the code.

```
  eventBus.on('moddleCopy.canCopyProperty', function(context) {
    ...
    // allow specific referenced elements to be copied
    // check whether the property is a reference and belongs to event definition
    if (isRefPropertyAllowed(property, parent)) {
      return property;
    }

```

I've already moved it from `copyProperty` to the event `canCopyProperty` where checks are being handled. Do you mean something else?

**Review by philippfromme — APPROVED** [review]
I've simplified the solution. We don't actually care about the event definition type but about the reference itself. Also, receive tasks weren't covered previously. I was also missing dedicated test coverage for the changed behavior.
