### PR TITLE
fix: empty whitespaces label in group

### LINKED ISSUE #2231: Group name/label with whitespaces only crashes modeler
### Describe the Bug

If the name/label of a group (= value of the referenced categoryValue) is initially set to a whitespace only string, the modeler crashes (= no useful interaction is possible anymore - can't move elements and creation of new elements is scuffed). 

This behavior does not occur, when the group already had a valid name/label before. My strong assumption is that the implicit creation of the categoryValue is not taking place in case of a whitespace only value.

### Steps to Reproduce

1. Create new model on [https://demo.bpmn.io/](https://demo.bpmn.io/)
2. Add a new group
3. Double click group for direct editing of the label
4. Enter a whitespace only string
5. Leave direct editing by clicking anywhere in the model

### Expected Behavior

No crash. Either the group should get no name/label at all or the whitespace string should be used.

### Environment

 - Browser: any
 - OS: any
 - Library version: 16+ (only tested in 16 and 17)

----

Crash report, visible in the console:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at LabelUtil.js:254:36
    at r (UpdateLabelHandler.js:54:5)
    at gy.execute (UpdateLabelHandler.js:89:12)
    at CommandStack.js:452:31
    at Kv._atomicDo (CommandStack.js:416:5)
    at Kv._internalExecute (CommandStack.js:445:8)
    at Kv.execute (CommandStack.js:186:8)
    at by.updateLabel (Modeling.js:106:22)
    at XA.update (LabelEditingProvider.js:495:18)
    at jb.complete (DirectEditing.js:105:21)
    at jb._handleKey (DirectEditing.js:140:17)
    at HTMLDivElement.o (helpers.ts:98:17)
```

### PR DESCRIPTION
**Pull request by abdul99ahad**
Closes #2231

### Proposed Changes

- Enter whitespaces in group labels doesn't crash modeler 
- Whitespaces will be treated as no label
 

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: lib/util/LabelUtil.js [hunk 1]
```diff
@@ -251,7 +251,10 @@ export function setLabel(element, text) {
   if (attr) {
 
     if (attr === 'categoryValueRef') {
-      semantic['categoryValueRef'].value = text;
+      if (!semantic[attr]) {
+        return;
```
Comment (nikku) [inline lib/util/LabelUtil.js:255]: Watch for the contract of this function. If you early return, I propose you `return element` to not break it.

Alternative: 

```
if (semantic[attr]) {
  // do change
}
```

My follow-up question is: Who calls this, and why, after the label has been removed? Will it ever be called with a non-empty text (in which case the above code would shadow a deeper issue?

Safe choice would be to be strict (ignore update only, if label is empty _and_ `categoryValueRef` is unset).

Comment (abdul99ahad) [reply lib/util/LabelUtil.js:255]: I would agree to early return the `element`. 

The `updateLabel` event calls this method. Even if we remove the existing label, it is updated via this method. It is not called after the label is removed, but rather when we are updating the label during `execute` lifecycle.

Comment (abdul99ahad) [reply lib/util/LabelUtil.js:255]: If the text is not empty, the `label.create` event will be fired and `setCategoryValue` function will be invoked in file `GroupBehavior.js`. So, in case the label is not empty, we will have `categoryValueRef`.

Comment (nikku) [inline lib/util/LabelUtil.js:255]:
```suggestion
        return element;
```

File: lib/util/LabelUtil.js [hunk 2]
```diff
@@ -251,7 +251,10 @@ export function setLabel(element, text) {
   if (attr) {
 
     if (attr === 'categoryValueRef') {
-      semantic['categoryValueRef'].value = text;
+      if (!semantic[attr]) {
```
Comment (nikku) [inline lib/util/LabelUtil.js:254]:
```suggestion
      
      // ignore update to non-existing category value when removing the text
      if (!text && !semantic[attr]) {
```

Comment (torge-hmn) [reply lib/util/LabelUtil.js:254]: This would match my first preferred suggestion of my initial approach: https://github.com/bpmn-io/bpmn-js/issues/2231#issuecomment-2351201757

It should be safe for all use cases - at least those I came across.

**Comment by philippfromme** [comment]
Apparently this is already on `main` but the PR is still open?!

**Review by philippfromme — APPROVED** [review]
