### PR TITLE
fix(create-append-anything): extend append shortcut use case

### LINKED ISSUE #1840: Append shortcut not working on elements without append menu
### Describe the Bug

As designed the append shortcut `a` can be used independent of the context: 

* Where append is possible `a` triggers append
* Where append is not possible `a` triggers create

This does not work in places where append is allowed in principle, but no append actions are given:

capture UYATWD_optimized

### Steps to Reproduce

1. Model event sub-process
2. Press `a`
3. __Observe nothing happens__

Can be reproduced on [demo.bpmn.io](https://demo.bpmn.io/s/start)

### Expected Behavior

As outlined above `a` should always be an available action (defaulting to create, if append is not applicable.

### Environment

 - Browser: Any
 - OS: Any
 - Library version: 11.3.0

### PR DESCRIPTION
**Pull request by smbea**
Closes #1840

I decided to move the "trigger create action if append not allowed" logic to the action itself. I figure this will also make it easier to use it in Camunda Modeler (no need to repeat logic, just trigger action). Let me know if you think this doesn't make sense

### CODE REVIEW

File: lib/features/create-append-anything/CreateAppendEditorActions.js [hunk 1]
```diff
@@ -25,16 +25,25 @@ CreateAppendEditorActions.prototype.registerActions = function() {
...
   // append
   if (selection && contextPad) {
     assign(actions, {
       'appendElement': function(event) {
-        contextPad.triggerEntry('append', 'click', event);
-      } }
-    );
+        const selected = selection && selection.get();
+
+        if (selected.length > 1) {
```
Comment (nikku) [inline lib/features/create-append-anything/CreateAppendEditorActions.js:38]: If we generalize it, let's generalize it the full way:

This part should not return, but trigger create.

**Review by nikku — CHANGES_REQUESTED** [review]
I like this direction.

Makes much more sense to have the switch contained in editor actions.

Just one tiny remark.

File: lib/features/create-append-anything/CreateAppendEditorActions.js [hunk 2]
```diff
@@ -25,16 +25,23 @@ CreateAppendEditorActions.prototype.registerActions = function() {
   var selection = this._injector.get('selection', false);
   var contextPad = this._injector.get('contextPad', false);
   var palette = this._injector.get('palette', false);
+  var popupMenu = this._injector.get('popupMenu', false);
 
   const actions = {};
 
   // append
   if (selection && contextPad) {
```
Comment (nikku) [inline lib/features/create-append-anything/CreateAppendEditorActions.js:33]: We'd like
```suggestion
  if (selection && contextPad && popupMenu && palette) {
```

**Review by nikku — APPROVED** [review]
